// sim/cities.ts — world financial hubs for the Kestrel simulation. Data is static and hand-curated; coordinates approximate city centers. utcOffset is the FIXED standard-time offset (no DST) — the sim must be deterministic and cannot depend on a timezone database.

export type Region = "na" | "sa" | "emea" | "apac";

export interface City {
	readonly id: string; // short lowercase slug, e.g. "nyc"
	readonly name: string; // display name, e.g. "New York"
	readonly lat: number;
	readonly lng: number;
	readonly region: Region;
	readonly weight: number; // 1-10 relative financial importance
	readonly currency: string; // ISO 4217 code of the local market
	readonly utcOffset: number; // hours from UTC, standard time, may be fractional
}

export const CITIES: readonly City[] = [
	{
		id: "amsterdam",
		name: "Amsterdam",
		lat: 52.3676,
		lng: 4.9041,
		region: "emea",
		weight: 6,
		currency: "EUR",
		utcOffset: 1,
	},
	{
		id: "atlanta",
		name: "Atlanta",
		lat: 33.749,
		lng: -84.388,
		region: "na",
		weight: 5,
		currency: "USD",
		utcOffset: -5,
	},
	{
		id: "auckland",
		name: "Auckland",
		lat: -36.8485,
		lng: 174.7633,
		region: "apac",
		weight: 3,
		currency: "NZD",
		utcOffset: 12,
	},
	{
		id: "bangalore",
		name: "Bangalore",
		lat: 12.9716,
		lng: 77.5946,
		region: "apac",
		weight: 5,
		currency: "INR",
		utcOffset: 5.5,
	},
	{
		id: "bangkok",
		name: "Bangkok",
		lat: 13.7563,
		lng: 100.5018,
		region: "apac",
		weight: 4,
		currency: "THB",
		utcOffset: 7,
	},
	{
		id: "beijing",
		name: "Beijing",
		lat: 39.9042,
		lng: 116.4074,
		region: "apac",
		weight: 7,
		currency: "CNY",
		utcOffset: 8,
	},
	{
		id: "bogota",
		name: "Bogotá",
		lat: 4.711,
		lng: -74.0721,
		region: "sa",
		weight: 4,
		currency: "COP",
		utcOffset: -5,
	},
	{
		id: "boston",
		name: "Boston",
		lat: 42.3601,
		lng: -71.0589,
		region: "na",
		weight: 6,
		currency: "USD",
		utcOffset: -5,
	},
	{
		id: "buenosaires",
		name: "Buenos Aires",
		lat: -34.6037,
		lng: -58.3816,
		region: "sa",
		weight: 5,
		currency: "ARS",
		utcOffset: -3,
	},
	{
		id: "charlotte",
		name: "Charlotte",
		lat: 35.2271,
		lng: -80.8431,
		region: "na",
		weight: 5,
		currency: "USD",
		utcOffset: -5,
	},
	{
		id: "chicago",
		name: "Chicago",
		lat: 41.8781,
		lng: -87.6298,
		region: "na",
		weight: 8,
		currency: "USD",
		utcOffset: -6,
	},
	{
		id: "dallas",
		name: "Dallas",
		lat: 32.7767,
		lng: -96.797,
		region: "na",
		weight: 5,
		currency: "USD",
		utcOffset: -6,
	},
	{
		id: "dc",
		name: "Washington DC",
		lat: 38.9072,
		lng: -77.0369,
		region: "na",
		weight: 6,
		currency: "USD",
		utcOffset: -5,
	},
	{
		id: "dubai",
		name: "Dubai",
		lat: 25.2048,
		lng: 55.2708,
		region: "emea",
		weight: 7,
		currency: "AED",
		utcOffset: 4,
	},
	{
		id: "dublin",
		name: "Dublin",
		lat: 53.3498,
		lng: -6.2603,
		region: "emea",
		weight: 5,
		currency: "EUR",
		utcOffset: 0,
	},
	{
		id: "frankfurt",
		name: "Frankfurt",
		lat: 50.1109,
		lng: 8.6821,
		region: "emea",
		weight: 8,
		currency: "EUR",
		utcOffset: 1,
	},
	{
		id: "hongkong",
		name: "Hong Kong",
		lat: 22.3193,
		lng: 114.1694,
		region: "apac",
		weight: 9,
		currency: "HKD",
		utcOffset: 8,
	},
	{
		id: "istanbul",
		name: "Istanbul",
		lat: 41.0082,
		lng: 28.9784,
		region: "emea",
		weight: 4,
		currency: "TRY",
		utcOffset: 3,
	},
	{
		id: "jakarta",
		name: "Jakarta",
		lat: -6.2088,
		lng: 106.8456,
		region: "apac",
		weight: 4,
		currency: "IDR",
		utcOffset: 7,
	},
	{
		id: "johannesburg",
		name: "Johannesburg",
		lat: -26.2041,
		lng: 28.0473,
		region: "emea",
		weight: 5,
		currency: "ZAR",
		utcOffset: 2,
	},
	{
		id: "la",
		name: "Los Angeles",
		lat: 34.0522,
		lng: -118.2437,
		region: "na",
		weight: 6,
		currency: "USD",
		utcOffset: -8,
	},
	{
		id: "lagos",
		name: "Lagos",
		lat: 6.5244,
		lng: 3.3792,
		region: "emea",
		weight: 3,
		currency: "NGN",
		utcOffset: 1,
	},
	{
		id: "lima",
		name: "Lima",
		lat: -12.0464,
		lng: -77.0428,
		region: "sa",
		weight: 3,
		currency: "PEN",
		utcOffset: -5,
	},
	{
		id: "london",
		name: "London",
		lat: 51.5074,
		lng: -0.1278,
		region: "emea",
		weight: 10,
		currency: "GBP",
		utcOffset: 0,
	},
	{
		id: "luxembourg",
		name: "Luxembourg",
		lat: 49.6116,
		lng: 6.1319,
		region: "emea",
		weight: 5,
		currency: "EUR",
		utcOffset: 1,
	},
	{
		id: "madrid",
		name: "Madrid",
		lat: 40.4168,
		lng: -3.7038,
		region: "emea",
		weight: 5,
		currency: "EUR",
		utcOffset: 1,
	},
	{
		id: "manila",
		name: "Manila",
		lat: 14.5995,
		lng: 120.9842,
		region: "apac",
		weight: 3,
		currency: "PHP",
		utcOffset: 8,
	},
	{
		id: "melbourne",
		name: "Melbourne",
		lat: -37.8136,
		lng: 144.9631,
		region: "apac",
		weight: 5,
		currency: "AUD",
		utcOffset: 10,
	},
	{
		id: "mexicocity",
		name: "Mexico City",
		lat: 19.4326,
		lng: -99.1332,
		region: "na",
		weight: 5,
		currency: "MXN",
		utcOffset: -6,
	},
	{
		id: "miami",
		name: "Miami",
		lat: 25.7617,
		lng: -80.1918,
		region: "na",
		weight: 5,
		currency: "USD",
		utcOffset: -5,
	},
	{
		id: "milan",
		name: "Milan",
		lat: 45.4642,
		lng: 9.19,
		region: "emea",
		weight: 5,
		currency: "EUR",
		utcOffset: 1,
	},
	{
		id: "montreal",
		name: "Montreal",
		lat: 45.5017,
		lng: -73.5673,
		region: "na",
		weight: 4,
		currency: "CAD",
		utcOffset: -5,
	},
	{
		id: "mumbai",
		name: "Mumbai",
		lat: 19.076,
		lng: 72.8777,
		region: "apac",
		weight: 7,
		currency: "INR",
		utcOffset: 5.5,
	},
	{
		id: "nyc",
		name: "New York",
		lat: 40.7128,
		lng: -74.006,
		region: "na",
		weight: 10,
		currency: "USD",
		utcOffset: -5,
	},
	{
		id: "paris",
		name: "Paris",
		lat: 48.8566,
		lng: 2.3522,
		region: "emea",
		weight: 7,
		currency: "EUR",
		utcOffset: 1,
	},
	{
		id: "riyadh",
		name: "Riyadh",
		lat: 24.7136,
		lng: 46.6753,
		region: "emea",
		weight: 5,
		currency: "SAR",
		utcOffset: 3,
	},
	{
		id: "santiago",
		name: "Santiago",
		lat: -33.4489,
		lng: -70.6693,
		region: "sa",
		weight: 4,
		currency: "CLP",
		utcOffset: -4,
	},
	{
		id: "saopaulo",
		name: "São Paulo",
		lat: -23.5505,
		lng: -46.6333,
		region: "sa",
		weight: 7,
		currency: "BRL",
		utcOffset: -3,
	},
	{
		id: "seattle",
		name: "Seattle",
		lat: 47.6062,
		lng: -122.3321,
		region: "na",
		weight: 5,
		currency: "USD",
		utcOffset: -8,
	},
	{
		id: "seoul",
		name: "Seoul",
		lat: 37.5665,
		lng: 126.978,
		region: "apac",
		weight: 7,
		currency: "KRW",
		utcOffset: 9,
	},
	{
		id: "sf",
		name: "San Francisco",
		lat: 37.7749,
		lng: -122.4194,
		region: "na",
		weight: 8,
		currency: "USD",
		utcOffset: -8,
	},
	{
		id: "shanghai",
		name: "Shanghai",
		lat: 31.2304,
		lng: 121.4737,
		region: "apac",
		weight: 8,
		currency: "CNY",
		utcOffset: 8,
	},
	{
		id: "shenzhen",
		name: "Shenzhen",
		lat: 22.5431,
		lng: 114.0579,
		region: "apac",
		weight: 6,
		currency: "CNY",
		utcOffset: 8,
	},
	{
		id: "singapore",
		name: "Singapore",
		lat: 1.3521,
		lng: 103.8198,
		region: "apac",
		weight: 9,
		currency: "SGD",
		utcOffset: 8,
	},
	{
		id: "stockholm",
		name: "Stockholm",
		lat: 59.3293,
		lng: 18.0686,
		region: "emea",
		weight: 4,
		currency: "SEK",
		utcOffset: 1,
	},
	{
		id: "sydney",
		name: "Sydney",
		lat: -33.8688,
		lng: 151.2093,
		region: "apac",
		weight: 7,
		currency: "AUD",
		utcOffset: 10,
	},
	{
		id: "taipei",
		name: "Taipei",
		lat: 25.033,
		lng: 121.5654,
		region: "apac",
		weight: 5,
		currency: "TWD",
		utcOffset: 8,
	},
	{
		id: "telaviv",
		name: "Tel Aviv",
		lat: 32.0853,
		lng: 34.7818,
		region: "emea",
		weight: 5,
		currency: "ILS",
		utcOffset: 2,
	},
	{
		id: "tokyo",
		name: "Tokyo",
		lat: 35.6895,
		lng: 139.6917,
		region: "apac",
		weight: 9,
		currency: "JPY",
		utcOffset: 9,
	},
	{
		id: "toronto",
		name: "Toronto",
		lat: 43.6532,
		lng: -79.3832,
		region: "na",
		weight: 7,
		currency: "CAD",
		utcOffset: -5,
	},
	{
		id: "warsaw",
		name: "Warsaw",
		lat: 52.2297,
		lng: 21.0122,
		region: "emea",
		weight: 4,
		currency: "PLN",
		utcOffset: 1,
	},
	{
		id: "zurich",
		name: "Zurich",
		lat: 47.3769,
		lng: 8.5417,
		region: "emea",
		weight: 7,
		currency: "CHF",
		utcOffset: 1,
	},
];

const BY_ID = new Map(CITIES.map((c) => [c.id, c]));

export function cityById(id: string): City {
	const city = BY_ID.get(id);
	if (!city) {
		throw new Error(`Unknown city: ${id}`);
	}
	return city;
}
